language: java
deploy:
  provider: heroku
  api_key:
    secure: FjWh1nvKJOwGRCpJU/pK64gfallUYXGAWZ+M85FP4+3AaX+laaBVd8Id6Q+CVXoAYN+LnZuZDpywbHKxCMJq3zdPc3viTbee7I1yvNLZ8Rw+7xLhzKTg8nWpZR45jujNfcRT5i3Z9/T/YzTQ1zAoGAdhahyx/b/kkdehSXgAYPY8hNJAWqsQ2Aa7lVKxkjmAAURsW1vU3kJvtpq1hxAV7r26I1PUjaDH/YgXjnUKLZuAJ0DoMtFmRlua5TuqVcQfSFe46NIpGEeTHaZ2xuLt4UbPnY+3n7n6E94f62Kw9EMYlEvKk84lxsKQUFk/EkKYlhZQLdNip2uBkuhZcJad7gDlRpONAIaqoscJOLqt1wjy5vg135fnI1P8lUG0iRor/kJGHanu2iU9A6f1UVEqljhH8pQtb8m33xV8A8jF+Spu1qpyiXmVFbHjMb6QRzts9vjn4t53xKryFV1iAQ4NSUdsL/CLuIEGoyIzdm4HL5wjp8erWJqw2Nqzy2j1k9eT0dU5apMeG8w+vl2UGV2SzdSLcVAPLp7wbAG6vAp5bwwuwusuf6k0MkwiNqIOrlfOBCF/IL7yW98ZVOHKP7c8mfI0h4XJ6cAIaLDM3zqVnj7ABGU/883GOkXGVGevJqmHN/ocnY4r2k8BEJP6QA5kbjb2HFncJqKvqJjiwkQ6vVA=
  strategy: git
